# -*- coding: utf-8 -*-
"""rag_core.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptI22JeSXm5CcOovbIVmepYwMQZiLSFX
"""

# rag_core.py
import os
import time
import json
from pathlib import Path

import numpy as np
import torch
import faiss

from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForCausalLM

os.environ["TRANSFORMERS_USE_LEGACY_CACHE"] = "1"


class BaseRAGPipeline:
    """
    Clean class-based RAG pipeline.
    Loads FAISS, metadata, encoder, and generator once.
    """

    def __init__(
        self,
        index_path: Path,
        emb_dir: Path,
        encoder_model: str = "Alibaba-NLP/gte-large-en-v1.5",
        generator_model: str = "microsoft/Phi-3.5-mini-instruct",
        max_new_tokens: int = 512,
    ):
        self.index_path = Path(index_path)
        self.emb_dir = Path(emb_dir)
        self.encoder_model = encoder_model
        self.generator_model = generator_model
        self.max_new_tokens = max_new_tokens

        print("\n🔹 Initializing RAG Pipeline...")
        self._load_faiss()
        self._load_metadata()
        self._load_encoder()
        self._load_llm()

    # ---------------------------------------------------------
    # Load FAISS index
    # ---------------------------------------------------------
    def _load_faiss(self):
        print("Loading FAISS index...")
        self.index = faiss.read_index(str(self.index_path))
        print(f"FAISS index loaded with {self.index.ntotal} vectors.\n")

    # ---------------------------------------------------------
    # Load metadata (no embeddings)
    # ---------------------------------------------------------
    def _load_metadata(self):
        print("Loading metadata...")
        meta = []

        for jf in sorted(self.emb_dir.glob("*.jsonl")):
            with jf.open("r", encoding="utf-8") as f:
                for line in f:
                    rec = json.loads(line)
                    rec.pop("embedding", None)  # drop vector to save RAM
                    meta.append(rec)

        self.meta = meta
        print(f"Metadata loaded: {len(meta)} rows.\n")

        if len(self.meta) != self.index.ntotal:
            print(
                f"[WARN] metadata rows ({len(self.meta)}) != index.ntotal ({self.index.ntotal})\n"
            )

    # ---------------------------------------------------------
    # Encoder (GTE)
    # ---------------------------------------------------------
    def _load_encoder(self):
        print("Loading query encoder...")
        self.encoder = SentenceTransformer(
            self.encoder_model,
            device="cpu",
            trust_remote_code=True
        )
        print("Encoder loaded.\n")

    # ---------------------------------------------------------
    # Generator (Phi model)
    # ---------------------------------------------------------
    def _load_llm(self):
        print("Loading generator model...")
        self.tok = AutoTokenizer.from_pretrained(self.generator_model)

        if self.tok.pad_token_id is None:
            self.tok.pad_token_id = self.tok.eos_token_id

        self.model = AutoModelForCausalLM.from_pretrained(
            self.generator_model,
            device_map="auto",
            torch_dtype=torch.float16,
            low_cpu_mem_usage=True,
            trust_remote_code=True,
        )
        print("Generator model loaded.\n")

    # ---------------------------------------------------------
    # Retrieval (returns results + fine-grained timings)
    # ---------------------------------------------------------
    def retrieve(self, query: str, k: int = 10):
        # --- Embedding time ---
        t0 = time.perf_counter()
        q_vec = self.encoder.encode(
            [query],
            normalize_embeddings=True,
            convert_to_numpy=True
        ).astype("float32")
        t1 = time.perf_counter()

        # --- FAISS search time ---
        scores, idx = self.index.search(q_vec, k)
        t2 = time.perf_counter()

        results = []
        for s, i in zip(scores[0], idx[0]):
            if i < 0:
                continue
            results.append({"score": float(s), **self.meta[int(i)]})

        timing = {
            "embedding_ms": (t1 - t0) * 1000,
            "retrieval_ms": (t2 - t1) * 1000,
        }
        return results, timing

    # ---------------------------------------------------------
    # Build text context
    # ---------------------------------------------------------
    def build_context(self, chunks, max_chars=1000):
        blocks = []
        for c in chunks:
            text = (c.get("text_for_embedding") or c.get("text") or "")[:max_chars]
            blocks.append(
                f"<chunk doc_id='{c.get('doc_id')}' page='{c.get('page')}' type='{c.get('type')}'>\n{text}\n</chunk>"
            )
        return "\n".join(blocks)

    # ---------------------------------------------------------
    # LLM answer generation
    # ---------------------------------------------------------
    def generate(self, query: str, context: str):
        SYSTEM = (
            "You are a meticulous research assistant.\n"
            "Answer ONLY using the provided <chunk> context.\n"
            "Go through EVERY chunk.\n"
            "Step 1: Extract EVERY distinct method/model by its PROPER NAME.\n"
            "Step 2: Write a concise answer.\n"
            "If nothing relevant: Not found.\n"
        )

        if not context.strip():
            return "Not found in the given context."

        prompt = (
            f"<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n{SYSTEM}\n"
            "<|eot_id|><|start_header_id|>user<|end_header_id|>\n"
            f"Question: {query}\n\n"
            f"{context}\n"
            "<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n"
        )

        inputs = self.tok(prompt, return_tensors="pt").to(self.model.device)

        out = self.model.generate(
            **inputs,
            max_new_tokens=self.max_new_tokens,
            do_sample=False,
            repetition_penalty=1.01,
            no_repeat_ngram_size=8,
            use_cache=False,
            eos_token_id=[
                self.tok.eos_token_id,
                self.tok.convert_tokens_to_ids("<|eot_id|>")
            ],
            pad_token_id=self.tok.pad_token_id,
        )

        gen_ids = out[:, inputs["input_ids"].shape[1]:]
        return self.tok.decode(gen_ids[0], skip_special_tokens=True).strip()

    # ---------------------------------------------------------
    # Full RAG pipeline
    # ---------------------------------------------------------
    def run(self, query: str, retrieve_chunks: int = 10):
        t0 = time.perf_counter()

        chunks, retr_timing = self.retrieve(query, k=retrieve_chunks)
        t1 = time.perf_counter()

        ctx = self.build_context(chunks)
        answer = self.generate(query, ctx)
        t2 = time.perf_counter()

        return {
            "query": query,
            "answer": answer,
            "contexts": chunks,
            "timing": {
                "embedding_ms": retr_timing["embedding_ms"],
                "retrieval_ms": retr_timing["retrieval_ms"],
                "generation_ms": (t2 - t1) * 1000,
                "total_ms": (t2 - t0) * 1000,
            },
            "config": {
                "encoder_model": self.encoder_model,
                "generator_model": self.generator_model,
                "retrieval_k": retrieve_chunks,
                "system_prompt_version": "v1",
                "max_new_tokens": self.max_new_tokens,
                "do_sample": False,
                "repetition_penalty": 1.01,
                "no_repeat_ngram_size": 8,
            },
        }